### ISSUE TITLE
Add IC and Bugsee as sponsors

### ISSUE THREAD

**Issue by piyushchauhan** [dsciitpatna/hack-o-latte#2]
Add Bugee, Incubation Center in the Sponsor Section 
https://www.bugsee.com/wp-content/themes/bugsee/assets/images/bugsee_logo.png
http://www.iciitp.com/wp-content/uploads/2019/07/Incubation-Center-IIT-Patna-Logo-Original-Colors.png

**Comment by shreyaswikriti** [comment]
done
